name: sg_mob
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - attrs=20.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - blas=1.0
  - bokeh=2.2.2
  - boost-cpp=1.74.0
  - branca=0.4.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.3
  - cfitsio=3.470
  - chardet=3.0.4
  - clangdev=5.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.6.0
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cryptography=3.1.1
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2.30.0
  - dask-core=2.30.0
  - decorator=4.4.2
  - descartes=1.1.0
  - distributed=2.30.0
  - entrypoints=0.3
  - expat=2.2.9
  - fiona=1.8.17
  - folium=0.11.0
  - freetype=2.10.4
  - freexl=1.0.5
  - fsspec=0.8.4
  - gdal=3.1.3
  - geopandas=0.8.1
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - glib=2.66.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icc_rt=2019.0.0
  - icu=67.1
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2019.4
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - kealib=1.4.13
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libffi=3.2.1
  - libflang=5.0.0
  - libgdal=3.1.3
  - libglib=2.66.1
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libpq=12.3
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.0
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - locket=0.2.0
  - lz4-c=1.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib-base=3.3.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - msgpack-python=1.0.0
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - networkx=2.5
  - numpy=1.19.2
  - olefile=0.46
  - openjpeg=2.3.1
  - openmp=5.0.0
  - openssl=1.1.1j
  - osmnx=0.16.1
  - packaging=20.4
  - pandas=1.1.3
  - parso=0.7.1
  - partd=1.1.0
  - patsy=0.5.1
  - pcre=8.44
  - pickleshare=0.7.5
  - pillow=8.0.0
  - pip=20.2.4
  - pixman=0.38.0
  - poppler=0.89.0
  - poppler-data=0.4.9
  - postgresql=12.3
  - proj=7.1.1
  - prompt-toolkit=3.0.8
  - psutil=5.7.2
  - pycairo=1.20.0
  - pycparser=2.20
  - pygments=2.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.6
  - python-dateutil=2.8.1
  - python-igraph=0.8.3
  - python_abi=3.8
  - pytz=2020.1
  - pywin32=228
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - requests=2.24.0
  - rtree=0.9.4
  - scikit-learn=0.23.2
  - scipy=1.5.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.15.0
  - sortedcontainers=2.2.2
  - sqlite=3.33.0
  - squarify=0.4.3
  - statsmodels=0.12.2
  - tblib=1.6.0
  - texttable=1.6.3
  - threadpoolctl=2.1.0
  - tiledb=2.1.1
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.0.4
  - tqdm=4.50.2
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - vc=14.1
  - vega_datasets=0.8.0
  - vs2015_runtime=14.16.27012
  - wcwidth=0.2.5
  - wheel=0.35.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zict=2.0.0
  - zipp=3.3.1
  - zlib=1.2.11
  - zstd=1.4.5
